import './globals.css';
import Footer from '@/components/Footer';
import { ShoppingBagProvider } from '@/contexts/ShoppingBagContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon/favicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <ShoppingBagProvider>
      <html lang='en'>
        <body>
          <main> {children}</main>
          <Footer />
        </body>
      </html>
    </ShoppingBagProvider>
  );
}
