import './globals.css';
import Footer from '@/components/Footer';
import { ShoppingBagProvider } from '@/contexts/ShoppingBagContext';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon/favicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <ShoppingBagProvider>
      <html lang='en'>
        <body>
          <main> {children}</main>
          <Footer />
          <ToastContainer position='bottom-center' />
        </body>
      </html>
    </ShoppingBagProvider>
  );
}
